
                <tr class="tr_white">
                    <td align="center">[field:title/]</td>
                    <td align="center">[field:id function="getaction(@me);"/]</td>
                    <td align="center">[field:openaction function="getopenaction(@me);"/]</td>
                    <td align="center">
                        <input type="button" onclick="window.location.href = 'vrpano_spot_edit.php?id=[field:id/]';" value="修改" class="btn1"/>
                        <input type="button" onclick="window.location.href = 'vrpano_spot_del.php?id=[field:id/]';" value="删除" class="btn1"/>
                    </td>
                </tr>
                