
                <tr class="tr_white">
                    <td align="center">[field:title /]</td>   
                    <td align="center">[field:uitype function="checktype(@me)"/]</td>
                    <td align="center">[field:openui function="checkopen(@me)"/]</td>
                    <td align="center">
                        <input type="button" onclick="window.location.href = 'vrpano_ui_edit.php?id=[field:id /]';" value="修改" class="btn1"/>
                        <input type="button" onclick="window.location.href = 'vrpano_ui_del.php?id=[field:id /]';" value="删除" class="btn1"/>
                    </td>
                </tr>
                