
                <tr class="tr_white">                                            
                    <td align="center">[field:title /]</td>   
                    <td align="center" height="90"><img src="[field:global.cfg_cmspath/]/vrpano/vrpano[field:pid/]/map/[field:file /]" height="80" /></td>    
                    <td align="center">
                        <input type="button" onclick="window.location.href = 'vrpano_manymap_edit.php?id=[field:id /]&page=[field:page /]'" value="修改" class="btn1"/>
                        <input type="button" onclick="window.location.href = 'vrpano_manymap_del.php?id=[field:id /]'" value="删除" class="btn1"/>
                    </td>
                </tr>
                