/* krpano 1.16.5 soundinterface plugin (build 2013-07-09) */
var krpanoplugin=function(){function z(){}function A(){var a=arguments;if(1<a.length){var b=String(a[0]).toLowerCase(),j=a[1],B=2<a.length?parseInt(a[2]):1,n=3<a.length?a[3]:null;if("auto"==b||"null"==b||""==b)b="autoid_"+g.timertick+"_"+Math.ceil(1E3*g.random);var a=j,f=a.split("|");if(1<f.length){if(null==h){h="";var k=document.createElement("audio");if(!(null===k||void 0===k))if(h+="wav",void 0!==k.canPlayType){var e=k.canPlayType("audio/ogg");e.match(/maybe|probably/i)&&(h+="ogg");e=k.canPlayType("audio/mpeg");
e.match(/maybe|probably/i)&&(h+="mp3");e=k.canPlayType("audio/mp4");e.match(/maybe|probably/i)&&(h+="mp4")}else h+="mp3"}k=f.length;if(0<=h.indexOf("mp3"))for(e=0;e<k;e++){var m=String(f[e]).toLowerCase();if(0<m.indexOf(".mp3")){a=f[e];break}}else if(0<=h.indexOf("mp4"))for(e=0;e<k;e++){if(m=String(f[e]).toLowerCase(),0<m.indexOf(".mp4")){a=f[e];break}}else if(0<=h.indexOf("ogg"))for(e=0;e<k;e++){if(m=String(f[e]).toLowerCase(),0<m.indexOf(".ogg")||0<m.indexOf(".oga")){a=f[e];break}}else if(0<=h.indexOf("wav"))for(e=
0;e<k;e++){if(m=String(f[e]).toLowerCase(),0<m.indexOf(".wav")){a=f[e];break}}else a=f[0]}f=w.rootpath;null!=f&&0<f.length&&"null"!=String(f).toLowerCase()?"/"!=f.charAt(f.length-1)&&(f+="/"):f="";var j=f=unescape(g.parsePath(f+a)),c=null;if(p&&x&&void 0!==d[b]){c=d[b];try{c.currentTime=0,c.pause()}catch(q){}d[b]=null;delete d[b];c=null}if(null!=c||void 0!==d[b]){null==c?c=d[b]:d[b]=c;try{c.currentTime=0,c.pause()}catch(u){}}else{c=document.createElement("audio");if(!c){g.trace(2,y);return}c.addEventListener("error",
function(){g.trace(3,"soundinterface - loading of "+j+" failed!");d[b]=null;delete d[b];c=null},!0);c.addEventListener("ended",function(){try{0<c.loopcount?(c.loopcount--,0==c.loopcount?n&&g.call(n):(c.currentTime=0,c.play())):(c.currentTime=0,c.play())}catch(a){}},!0);d[b]=c}try{if(c.loopcount=B,c.src=j,c&&(c.volume=r,c.play()),p&&c&&c.paused){var s=document.body,t=function(){try{s.removeEventListener("touchstart",t,!0),l&&l.paused&&!l.ended&&l.play()}catch(a){l=null}};s.removeEventListener("touchstart",
t,!0);l=c;s.addEventListener("touchstart",t,!0)}}catch(v){g.trace(2,y)}}}function C(a){if(a=d[String(a).toLowerCase()])try{a.pause()}catch(b){}}function D(a){if(a=d[String(a).toLowerCase()])try{a.paused&&a.play()}catch(b){}}function E(a){if(a=d[String(a).toLowerCase()])try{a.paused?a.play():a.pause()}catch(b){}}function F(a){if(a=d[String(a).toLowerCase()]){a==l&&(l=null);try{a.currentTime=0,a.pause()}catch(b){}}}function G(){var a,b;for(a in d)if((b=d[a])&&void 0!==b.paused){try{b.pause()}catch(j){}d[a]=
null}d=[];l=null}function u(a){var b,j;for(b in d){j=d[b];try{j&&void 0!==j.paused&&(!1==a?!1==j.paused&&(j.pause(),j.needresume=!0):j.needresume&&j.play())}catch(g){}}}function v(){r=n?0:q;var a,b;for(a in d)if(b=d[a])try{b.volume=r,p&&(n?!1==b.paused&&(b._krp_muted=!0,b.pause()):!0==b._krp_muted&&(b._krp_muted=!1,b.play()))}catch(j){}}var w=null,g=null,d=[],l=null,p=!1,x=!1,y="soundinterface - HTML5 audio is not supported by this browser!",q=1,n=!1,r=1;this.registerplugin=function(a,b,d){g=a;w=
d;d.keep=!0;d.registerattribute("rootpath","");d.registerattribute("volume",1,function(a){q=a;v()},function(){return q});d.registerattribute("mute",!1,function(a){n=0<="yesontrue1".indexOf(String(a).toLowerCase());v()},function(){return n});g.soundinterface=d;g.preloadsound=z;g.playsound=A;g.pausesound=C;g.resumesound=D;g.pausesoundtoggle=E;g.stopsound=F;g.stopallsounds=G;a=navigator.userAgent;b=a.indexOf("OS ");0<b&&(b+=3,"4.2">a.slice(b,a.indexOf(" ",b)).split("_").join(".")&&(x=!0));p=g.isphone||
g.ispad;window&&(window.addEventListener("pagehide",function(){u(!1)},!0),window.addEventListener("pageshow",function(){u(!0)},!0))};var h=null};
